name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Docker Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd ${{ secrets.DEPLOY_PATH }}

            echo "== Rama y commit =="
            git branch --show-current
            git log -1 --oneline

            echo "== Sincronizando repo =="
            git fetch origin
            git checkout -B production origin/production
            git reset --hard origin/production
            git clean -fd

            echo "== Docker deploy =="
            docker compose down
            docker compose build --no-cache
            docker compose up -d
